SURVEY_QUESTIONS = [
    # ── Agotamiento Emocional — 9 ítems, escala 0-6 ──────────────────────────
    {"id": "q1",  "block": "mbi", "dimension": "exhaustion", "scale_min": 0, "scale_max": 6,
     "text": "Me siento emocionalmente agotado/a por mi trabajo"},
    {"id": "q2",  "block": "mbi", "dimension": "exhaustion", "scale_min": 0, "scale_max": 6,
     "text": "Me siento agotado/a al terminar la jornada laboral"},
    {"id": "q3",  "block": "mbi", "dimension": "exhaustion", "scale_min": 0, "scale_max": 6,
     "text": "Me siento cansado/a cuando me levanto y tengo que enfrentar otro día de trabajo"},
    {"id": "q4",  "block": "mbi", "dimension": "exhaustion", "scale_min": 0, "scale_max": 6,
     "text": "Trabajar todo el día es realmente una tensión para mí"},
    {"id": "q5",  "block": "mbi", "dimension": "exhaustion", "scale_min": 0, "scale_max": 6,
     "text": "Me siento frustrado/a por mi trabajo"},
    {"id": "q6",  "block": "mbi", "dimension": "exhaustion", "scale_min": 0, "scale_max": 6,
     "text": "Me siento como si estuviera al límite de mis posibilidades"},
    {"id": "q7",  "block": "mbi", "dimension": "exhaustion", "scale_min": 0, "scale_max": 6,
     "text": "Trabajar en contacto directo con la gente me produce estrés"},
    {"id": "q8",  "block": "mbi", "dimension": "exhaustion", "scale_min": 0, "scale_max": 6,
     "text": "Siento que mi trabajo me está desgastando"},
    {"id": "q9",  "block": "mbi", "dimension": "exhaustion", "scale_min": 0, "scale_max": 6,
     "text": "Me siento quemado/a por mi trabajo"},
    # ── Despersonalización / Cinismo — 5 ítems, escala 0-6 ───────────────────
    {"id": "q10", "block": "mbi", "dimension": "depersonalization", "scale_min": 0, "scale_max": 6,
     "text": "Siento que trato a algunas personas como si fueran objetos impersonales"},
    {"id": "q11", "block": "mbi", "dimension": "depersonalization", "scale_min": 0, "scale_max": 6,
     "text": "Me he vuelto más insensible con la gente desde que ejerzo este trabajo"},
    {"id": "q12", "block": "mbi", "dimension": "depersonalization", "scale_min": 0, "scale_max": 6,
     "text": "Me preocupa que este trabajo me esté endureciendo emocionalmente"},
    {"id": "q13", "block": "mbi", "dimension": "depersonalization", "scale_min": 0, "scale_max": 6,
     "text": "Realmente no me importa lo que les ocurra a las personas con las que trabajo"},
    {"id": "q14", "block": "mbi", "dimension": "depersonalization", "scale_min": 0, "scale_max": 6,
     "text": "Me he vuelto más cínico/a respecto al valor de mi trabajo"},
    # ── Realización Personal — 8 ítems, escala 0-6, puntuación INVERTIDA ─────
    {"id": "q15", "block": "mbi", "dimension": "achievement", "scale_min": 0, "scale_max": 6,
     "text": "Siento que estoy influyendo positivamente en la vida de otras personas a través de mi trabajo"},
    {"id": "q16", "block": "mbi", "dimension": "achievement", "scale_min": 0, "scale_max": 6,
     "text": "Me siento muy activo/a en mi trabajo"},
    {"id": "q17", "block": "mbi", "dimension": "achievement", "scale_min": 0, "scale_max": 6,
     "text": "Puedo entender fácilmente cómo se sienten las personas con las que trabajo"},
    {"id": "q18", "block": "mbi", "dimension": "achievement", "scale_min": 0, "scale_max": 6,
     "text": "Trato con mucha efectividad los problemas de las personas"},
    {"id": "q19", "block": "mbi", "dimension": "achievement", "scale_min": 0, "scale_max": 6,
     "text": "Siento que estoy contribuyendo positivamente con mi trabajo"},
    {"id": "q20", "block": "mbi", "dimension": "achievement", "scale_min": 0, "scale_max": 6,
     "text": "Me siento estimulado/a después de trabajar junto a otras personas"},
    {"id": "q21", "block": "mbi", "dimension": "achievement", "scale_min": 0, "scale_max": 6,
     "text": "Creo que consigo muchas cosas valiosas en este trabajo"},
    {"id": "q22", "block": "mbi", "dimension": "achievement", "scale_min": 0, "scale_max": 6,
     "text": "En mi trabajo, trato los problemas con mucha calma"},
    # ── Clima Organizacional — 6 ítems, escala 1-5 ───────────────────────────
    {"id": "q23", "block": "climate", "dimension": "communication",  "scale_min": 1, "scale_max": 5,
     "text": "La información fluye claramente en mi equipo"},
    {"id": "q24", "block": "climate", "dimension": "recognition",    "scale_min": 1, "scale_max": 5,
     "text": "Mi trabajo es valorado por mis superiores"},
    {"id": "q25", "block": "climate", "dimension": "workload",       "scale_min": 1, "scale_max": 5,
     "text": "Mi carga de trabajo es manejable"},
    {"id": "q26", "block": "climate", "dimension": "relationships",  "scale_min": 1, "scale_max": 5,
     "text": "Las relaciones con mis compañeros son positivas"},
    {"id": "q27", "block": "climate", "dimension": "autonomy",       "scale_min": 1, "scale_max": 5,
     "text": "Tengo libertad para tomar decisiones en mi rol"},
    {"id": "q28", "block": "climate", "dimension": "leadership",     "scale_min": 1, "scale_max": 5,
     "text": "Mi líder me apoya cuando lo necesito"},
]

MBI_QUESTIONS = [q for q in SURVEY_QUESTIONS if q["block"] == "mbi"]
CLIMATE_QUESTIONS = [q for q in SURVEY_QUESTIONS if q["block"] == "climate"]
